### ISSUE TITLE
[Bug & Reproducibility] Padding tokens are not accounted

### ISSUE THREAD

**Issue by alexdremov** [glassroom/heinsen_routing_2022_paper#1]
The provided code for text classification does not take into account padding positions. Even though routing algorithm has `mask` argument to address that, it is not used.

https://github.com/glassroom/heinsen_routing_2022_paper/blob/f432c5ede59ece726cd56faaf4a50b27677bc202/models.py#L40-L45

Therefore, predictions depend on number of padding tokens in sequence, which makes results non-reproducible and almost random. Model can produce different prediction for the same sample with different batching shuffle random seed.

**Comment by fheinsen** [comment]
Thank you. I did that _on purpose_ to induce the routing algorithm to learn to ignore (varying numbers of) padding tokens. Remarkably, the algorithm learns to do exactly that. The downside is that if you train the classification head on a small dataset for only a few epochs, you _might_ see a slight variation in test-set accuracy when you shuffle test samples. This is important, so I will add a direct link to your comment on the README. Thank you for pointing it out!

**Comment by fheinsen** [comment]
I added a link to this issue on the README. I will leave the code as is, for the record. Thank you again for pointing this out!

**Comment by alexdremov** [comment]
Thanks for clarification! Indeed, my problem's domain consists of short texts mostly. I believe that also contributes to the result as there can be quite a lot of padding positions. 

I created this issue as I noticed such artifacts in my model's predictions. 

In fact, explicit masking improved overall score as well as guaranteed reproducibility.
